version: 0.1
keywords: "HTML, Javascript, Visual Experience"
title: "Seeker #2"
description: "Seeker #2 is a visual experience about blind walkers with dice. They throw it on move based on score to reach a remote destination"
url: "http://behrooz-tahanzadeh.github.io/walker-1/"
date: "September 2014"
googleAnalyticsCode: "UA-40560087-5"
